GET http://localhost:8090/price/matic
###

GET http://localhost:8090/

###
GET http://localhost:8090/routerInfo/?tokenA=0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270&tokenB=0x2791bca1f2de4661ed88a30c99a7a9449aa84174&amount=100&key=PAMdGzKWp1e/9skFRz..nc4geF.

###

GET http://localhost:8090/authenticate/?email=sevenisalie@gmail.com&ethAddress=0x2791bca1f2de4661ed88a30c99a7a9449aa84174


###

POST http://localhost:8090/authenticate/createUser
Content-Type: application/json

{
    "username": "0xAEFac7De344509cc05fB806898E18C8B8bD0024c",
    "password": "poopballs"
}
###

POST http://localhost:8090/authenticate/login
Content-Type: application/json

{
    "username": "0xAEFac7De344509cc05fB806898E18C8B8bD0024c",
    "password": "poopballs"
}

